# Generated by Django 4.2.16 on 2024-09-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='winner',
            new_name='bid_winner',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='start_bid',
        ),
    ]
