# Generated by Django 4.2.16 on 2024-10-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_winner_auctionlisting_bid_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='active',
        ),
    ]
